import React, { useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { BarChart3, MapPin, Wallet } from 'lucide-react-native';
import { useDriverTripHistory, Period } from '@/hooks/useDriverTripHistory';

export default function TripsHistory({ driverId }: { driverId: string | null }) {
  const [period, setPeriod] = useState<Period>('today');
  const { trips, loading, error, totalEarnings } = useDriverTripHistory(driverId, period);
  const tripCount = trips.filter((trip) => trip.workflowType === 'direct_trip').length;
  const deliveryCount = trips.filter((trip) => trip.workflowType === 'store_delivery').length;
  return <View style={styles.screen}>
    <View style={styles.header}><Text style={styles.title}>Trips History</Text></View>
    <View style={styles.tabs}>{(['today', 'week', 'month'] as Period[]).map((item) => <TouchableOpacity key={item} onPress={() => setPeriod(item)} style={[styles.tab, period === item && styles.activeTab]}><Text style={[styles.tabText, period === item && styles.activeTabText]}>{item[0].toUpperCase() + item.slice(1)}</Text></TouchableOpacity>)}</View>
    <ScrollView contentContainerStyle={styles.content}>
      <View style={styles.summary}><View style={styles.summaryBlock}><View style={styles.iconBox}><BarChart3 color="#2675F5" size={24} /></View><Text style={styles.summaryLabel}>Total Trips</Text><Text style={styles.summaryValue}>{trips.length}</Text><View style={styles.breakdown}><Text style={styles.breakdownText}>Trips {tripCount}</Text><Text style={styles.breakdownText}>Deliveries {deliveryCount}</Text></View></View><View style={styles.divider} /><View style={styles.summaryBlock}>
<View style={styles.iconBox}><Wallet color="#2675F5" size={24} /></View><Text style={styles.summaryLabel}>Total Earnings</Text><Text style={styles.summaryValue}>ZMW {totalEarnings.toFixed(2)}</Text></View></View>
      {loading ? <ActivityIndicator color="#2675F5" size="large" style={styles.state} /> : error ? <Text style={styles.stateText}>{error}</Text> : trips.length === 0 ? <Text style={styles.stateText}>No completed trips for this period.</Text> : trips.map((trip) => <View style={styles.tripCard} key={trip.id}><View style={styles.route}><MapPin color="#2675F5" size={23} /><View style={styles.dash} /><MapPin color="#2675F5" size={23} fill="#2675F5" /></View><View style={styles.addresses}><Text style={styles.address}>{trip.pickup}</Text><Text style={styles.address}>{trip.destination}</Text></View><View style={styles.money}><Text style={styles.amount}>ZMW {trip.amount.toFixed(2)}</Text><View style={[styles.typeBadge, trip.workflowType === 'store_delivery' && styles.deliveryBadge]}><Text style={styles.typeBadgeText}>{trip.workflowType === 'store_delivery' ? 'Delivery' : 'Trip'}</Text></View><Text style={styles.time}>{trip.createdAt?.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text></View></View>)}
    </ScrollView>
  </View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#F4F5F8' }, header: { height: 92, paddingHorizontal: 28, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { fontSize: 22, fontWeight: '700', color: '#121722' }, tabs: { flexDirection: 'row', gap: 12, paddingHorizontal: 30, paddingBottom: 22 }, tab: { flex: 1, height: 58, borderRadius: 30, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' }, activeTab: { backgroundColor: '#2675F5' }, tabText: { fontSize: 14, fontWeight: '600', color: '#171A22' }, activeTabText: { color: '#fff' }, content: { padding: 16, paddingBottom: 126, gap: 12 }, summary: { backgroundColor: '#fff', borderRadius: 12, padding: 28, flexDirection: 'row', alignItems: 'center', shadowColor: '#000', shadowOpacity: .08, shadowRadius: 12, elevation: 3 }, summaryBlock: { flex: 1, alignItems: 'center', gap: 10 }, iconBox: { backgroundColor: '#EAF2FF', borderRadius: 14, padding: 10 }, summaryLabel: { fontSize: 15, color: '#202532' }, summaryValue: { fontSize: 20, fontWeight: '800', color: '#10131A' }, divider: { height: 150, width: 1, backgroundColor: '#E0E2E7' }, tripCard: { backgroundColor: '#fff', borderRadius: 12, padding: 24, flexDirection: 'row', alignItems: 'center', shadowColor: '#000', shadowOpacity: .06, shadowRadius: 10, elevation: 2 }, route: { width: 38, alignItems: 'center' }, dash: { height: 30, borderLeftWidth: 2, borderStyle: 'dashed', borderColor: '#2675F5' }, addresses: { flex: 1, gap: 14 }, address: { fontSize: 15, color: '#202532' }, money: { alignItems: 'flex-end', gap: 8 }, amount: { fontSize: 17, fontWeight: '800', color: '#10131A' }, typeBadge: { backgroundColor: '#EAF2FF', borderRadius: 10, paddingHorizontal: 8, paddingVertical: 3 }, deliveryBadge: { backgroundColor: '#FFF3D6' }, typeBadgeText: { fontSize: 11, fontWeight: '700', color: '#2675F5' }, breakdown: { flexDirection: 'row', gap: 8 }, breakdownText: { fontSize: 11, color: '#727987' }, time: { fontSize: 13, color: '#727987' }, state: { marginTop: 60 }, stateText: { textAlign: 'center', color: '#727987', fontSize: 16, marginTop: 50 } });
